[recipes]
std = { type = "mesy_test" }
nontof = { type = "histo_std" }
tof = { type = "tof_std" }

[modules.mcpd0]
id = 0
recipe = "std"
type = "mesy"
is_master = true
mcpd_id = 0
#local = "testdata/00678408.mdat"
#remote = ""
local = "localhost:54322"
remote = "localhost:54321"
cells = {}
modules = {}

[postprocess_modes]
default = "nontof"
tof = "tof"

[histogram]
nx = 1024
ny = 1024
max_nt = 1024
