[modules]
ts01 = { type = "ge", source = "localhost:50020", timestamper = true }
ep01 = { type = "ge", source = "localhost:50001" }
ep02 = { type = "ge", source = "localhost:50002" }
ep03 = { type = "ge", source = "localhost:50003" }
ep04 = { type = "ge", source = "localhost:50004" }
ep05 = { type = "ge", source = "localhost:50005" }
ep06 = { type = "ge", source = "localhost:50006" }
ep07 = { type = "ge", source = "localhost:50007" }
ep08 = { type = "ge", source = "localhost:50008" }
ep09 = { type = "ge", source = "localhost:50009" }
ep10 = { type = "ge", source = "localhost:50010" }
ep11 = { type = "ge", source = "localhost:50011" }
ep12 = { type = "ge", source = "localhost:50012" }
ep13 = { type = "ge", source = "localhost:50013" }
ep14 = { type = "ge", source = "localhost:50014" }
ep15 = { type = "ge", source = "localhost:50015" }
ep16 = { type = "ge", source = "localhost:50016" }
ep17 = { type = "ge", source = "localhost:50017" }
ep18 = { type = "ge", source = "localhost:50018" }
