[modules]
ts01 = { type = "ge", source = "testdata/ts", timestamper = true }
ep01 = { type = "ge", source = "testdata/00" }
ep02 = { type = "ge", source = "testdata/01" }
ep03 = { type = "ge", source = "testdata/02" }
ep04 = { type = "ge", source = "testdata/03" }
ep05 = { type = "ge", source = "testdata/04" }
ep06 = { type = "ge", source = "testdata/05" }
ep07 = { type = "ge", source = "testdata/06" }
ep08 = { type = "ge", source = "testdata/07" }
ep09 = { type = "ge", source = "testdata/08" }
ep10 = { type = "ge", source = "testdata/09" }
ep11 = { type = "ge", source = "testdata/10" }
ep12 = { type = "ge", source = "testdata/11" }
ep13 = { type = "ge", source = "testdata/12" }
ep14 = { type = "ge", source = "testdata/13" }
ep15 = { type = "ge", source = "testdata/14" }
ep16 = { type = "ge", source = "testdata/15" }
ep17 = { type = "ge", source = "testdata/16" }
ep18 = { type = "ge", source = "testdata/17" }
