[modules]
ts01 = { type = "ge", source = "testdata/ts", timestamper = true }
ep01 = { type = "ge", source = "testdata/00" }
ep02 = { type = "ge", source = "testdata/01" }
ep03 = { type = "ge", source = "testdata/02" }
ep04 = { type = "ge", source = "testdata/03" }
ep05 = { type = "ge", source = "testdata/04" }
ep06 = { type = "ge", source = "testdata/05" }
ep07 = { type = "ge", source = "testdata/06" }
ep08 = { type = "ge", source = "testdata/07" }
ep09 = { type = "ge", source = "testdata/08" }
ep10 = { type = "ge", source = "testdata/09" }
ep11 = { type = "ge", source = "testdata/10" }
ep12 = { type = "ge", source = "testdata/11" }
ep13 = { type = "ge", source = "testdata/12" }
ep14 = { type = "ge", source = "testdata/13" }
ep15 = { type = "ge", source = "testdata/14" }
ep16 = { type = "ge", source = "testdata/15" }
ep17 = { type = "ge", source = "testdata/16" }
ep18 = { type = "ge", source = "testdata/17" }

ne16 = { type = "canon", source = "testdata/overnight_MoDi_2025-07-14_16-53-45_16.dump"}
ne17 = { type = "canon", source = "testdata/overnight_MoDi_2025-07-14_16-53-45_17.dump"}
ne18 = { type = "canon", source = "testdata/overnight_MoDi_2025-07-14_16-53-45_18.dump"}
ne19 = { type = "canon", source = "testdata/overnight_MoDi_2025-07-14_16-53-45_19.dump"}
ne20 = { type = "canon", source = "testdata/overnight_MoDi_2025-07-14_16-53-45_20.dump"}
ne21 = { type = "canon", source = "testdata/overnight_MoDi_2025-07-14_16-53-45_21.dump"}
ne22 = { type = "canon", source = "testdata/overnight_MoDi_2025-07-14_16-53-45_22.dump"}
ne23 = { type = "canon", source = "testdata/overnight_MoDi_2025-07-14_16-53-45_23.dump"}
ne24 = { type = "canon", source = "testdata/overnight_MoDi_2025-07-14_16-53-45_24.dump"}
ne27 = { type = "canon", source = "testdata/overnight_MoDi_2025-07-14_16-53-45_27.dump"}
