[modules.stamper]
type = "ge"
ts = true
addr = "localhost:50020"

[modules]
ep01 = { type = "ge", addr = "localhost:50001" }

[modules.ep02]
type = "ge"
addr = "localhost:50002"

[modules.ep03]
type = "ge"
addr = "localhost:50003"

[modules.ep04]
type = "ge"
addr = "localhost:50004"

[modules.ep05]
type = "ge"
addr = "localhost:50005"

[modules.ep06]
type = "ge"
addr = "localhost:50006"

[modules.ep07]
type = "ge"
addr = "localhost:50007"

[modules.ep08]
type = "ge"
addr = "localhost:50008"

[modules.ep09]
type = "ge"
addr = "localhost:50009"

[modules.ep10]
type = "ge"
addr = "localhost:50010"

[modules.ep11]
type = "ge"
addr = "localhost:50011"

[modules.ep12]
type = "ge"
addr = "localhost:50012"

[modules.ep13]
type = "ge"
addr = "localhost:50013"

[modules.ep14]
type = "ge"
addr = "localhost:50014"

[modules.ep15]
type = "ge"
addr = "localhost:50015"

[modules.ep16]
type = "ge"
addr = "localhost:50016"

[modules.ep17]
type = "ge"
addr = "localhost:50017"

[modules.ep18]
type = "ge"
addr = "localhost:50018"
