[recipes]
ge = { type = "kws_ge", reso_1024 = false, rebin_8x8 = true }
nontof = { type = "histo_std" }
tof = { type = "tof_std" }

[modules]
ep01 = { id = 0,  recipe = "ge", type = "ge", source = "testdata/00" }
ep02 = { id = 1,  recipe = "ge", type = "ge", source = "testdata/01" }
ep03 = { id = 2,  recipe = "ge", type = "ge", source = "testdata/02" }
ep04 = { id = 3,  recipe = "ge", type = "ge", source = "testdata/03" }
ep05 = { id = 4,  recipe = "ge", type = "ge", source = "testdata/04" }
ep06 = { id = 5,  recipe = "ge", type = "ge", source = "testdata/05" }
ep07 = { id = 6,  recipe = "ge", type = "ge", source = "testdata/06" }
ep08 = { id = 7,  recipe = "ge", type = "ge", source = "testdata/07" }
ep09 = { id = 8,  recipe = "ge", type = "ge", source = "testdata/08" }
ep10 = { id = 9,  recipe = "ge", type = "ge", source = "testdata/09" }
ep11 = { id = 10, recipe = "ge", type = "ge", source = "testdata/10" }
ep12 = { id = 11, recipe = "ge", type = "ge", source = "testdata/11" }
ep13 = { id = 12, recipe = "ge", type = "ge", source = "testdata/12" }
ep14 = { id = 13, recipe = "ge", type = "ge", source = "testdata/13" }
ep15 = { id = 14, recipe = "ge", type = "ge", source = "testdata/14" }
ep16 = { id = 15, recipe = "ge", type = "ge", source = "testdata/15" }
ep17 = { id = 16, recipe = "ge", type = "ge", source = "testdata/16" }
ep18 = { id = 17, recipe = "ge", type = "ge", source = "testdata/17" }
ts01 = { id = 18, recipe = "ge", type = "ge", source = "testdata/ts", timestamper = true }

[process_modes]
default = "nontof"
tof = "tof"

[histogram]
nx = 144
ny = 256
max_nt = 1024
