[inputs.mcpd0]
id = 0
type = "mesy"
recipe = "mpsd"
local = "0.0.0.0:54400"
remote = "192.168.168.130:54321"
mcpd_id = 0
is_master = true
terminate = true
cells = {}
modules = {
    "0" = { gain = 92, threshold = 22 },
    "1" = { gain = 92, threshold = 22 },
    "2" = { gain = 92, threshold = 22 },
    "3" = { gain = 92, threshold = 22 },
    "4" = { gain = 92, threshold = 22 },
    "5" = { gain = 92, threshold = 22 },
    "6" = { gain = 92, threshold = 22 },
    "7" = { gain = 92, threshold = 22 },
}

[inputs.mcpd1]
id = 1
type = "mesy"
recipe = "mpsd"
local = "0.0.0.0:54402"
remote = "192.168.168.131:54321"
mcpd_id = 1
is_master = false
terminate = false
cells = {}
modules = {
    "0" = { gain = 92, threshold = 22 },
    "1" = { gain = 92, threshold = 22 },
    "2" = { gain = 92, threshold = 22 },
    "3" = { gain = 92, threshold = 22 },
    "4" = { gain = 92, threshold = 22 },
    "5" = { gain = 92, threshold = 22 },
    "6" = { gain = 92, threshold = 22 },
    "7" = { gain = 92, threshold = 22 },
}

[inputs.mcpd2]
id = 2
type = "mesy"
recipe = "mpsd"
local = "0.0.0.0:54404"
remote = "192.168.168.132:54321"
mcpd_id = 2
is_master = false
terminate = false
cells = {}
modules = {
    "0" = { gain = 92, threshold = 22 },
    "1" = { gain = 92, threshold = 22 },
    "2" = { gain = 92, threshold = 22 },
    "3" = { gain = 92, threshold = 22 },
    "4" = { gain = 92, threshold = 22 },
    "5" = { gain = 92, threshold = 22 },
    "6" = { gain = 92, threshold = 22 },
    "7" = { gain = 92, threshold = 22 },
}

[inputs.mcpd3]
id = 3
type = "mesy"
recipe = "mpsd"
local = "0.0.0.0:54406"
remote = "192.168.168.133:54321"
mcpd_id = 3
is_master = false
terminate = false
cells = {}
modules = {
    "0" = { gain = 92, threshold = 22 },
    "1" = { gain = 92, threshold = 22 },
    "2" = { gain = 92, threshold = 22 },
    "3" = { gain = 92, threshold = 22 },
    "4" = { gain = 92, threshold = 22 },
    "5" = { gain = 92, threshold = 22 },
    "6" = { gain = 92, threshold = 22 },
    "7" = { gain = 92, threshold = 22 },
}

[inputs.mcpd4]
id = 4
type = "mesy"
recipe = "mpsd"
local = "0.0.0.0:54408"
remote = "192.168.168.134:54321"
mcpd_id = 4
is_master = false
terminate = true
cells = {}
modules = {
    "0" = { gain = 92, threshold = 22 },
    "1" = { gain = 92, threshold = 22 },
    "2" = { gain = 92, threshold = 22 },
    "3" = { gain = 92, threshold = 22 },
    "4" = { gain = 92, threshold = 22 },
    "5" = { gain = 92, threshold = 22 },
    "6" = { gain = 92, threshold = 22 },
    "7" = { gain = 92, threshold = 22 },
}

[input_recipes]
mpsd = { type = "mesy_mpsd" }

[process_modes]
tof = { type = "histo_tof" }
notof = { type = "histo_std" }
default = "notof"

[outputs]
diag = { type = "diag" }

[outputs.aux]
type = "aux_histo"

[[outputs.aux.histos]]
name = "Amplitude spectrum"
filter = "evtype == neutron"
x = { expr = "ampl", bins = 256, min = 0, max = 1023 }

[histogram]
nx = 288
ny = 1024
max_nt = 1
